config/routes.rb
Rails.application.routes.draw do
 
root 'customers#index', as: 'home'


	get 'customers/blacklist' => 'customers#blacklist', as: 'blacklist'
		resources :customers do
    collection do
     get :toggle_blacklist
    end
  end
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
	validates :name,  presence: true, length: {minimum: 1}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blist_controller.rb
class BlistController < ApplicationController
	def blacklist
		
	end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	def index
		@customer = Customer.all
	end
	def blacklist
		@customer = Customer.all
	end

	def new
		@customer = Customer.new
	end

	def show
		@customer = Customer.find(params[:id])

	end

	def edit
		@customer = Customer.find(params[:id])

	end

	def update
		
		@customer = Customer.last

		if(@customer.update(customer_params))
			redirect_to @customer
		else
			render 'edit'
		end
	end

	def create
			@customer = Customer.new(customer_params)

		if(@customer.save)
			redirect_to @customer

		else
			render 'new'
		end
	end

	def toggle_blacklist
		 @customer = Customer.find(params[:customer_id])
		if  @customer.blklist == false
				@blklist = @customer.update(blklist: true )
		else 
			  @blklist = @customer.update(blklist: false)
		end
				redirect_to @customer
	end




	private def customer_params
						 	 			params.require(:customer).permit(:name, :number, :description, :blklist)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blist_helper.rb
module BlistHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/blacklist.html.erb
<h2>Черный список клиентов</h2>


	<%= form_for :search do |f| %>
	<p>
			<h4>добавление в список по номеру телефона:</h4>
			<%= f.text_field :blklist %>
	</p>
	
	<% end %>
  


<hr>
<% @customer.each do |customer| %>
	<% if customer.blklist == true %>
	<div>
		<h4>Имя:						<%= customer.name %></h4>
		<p> Номер телефона:	<%= customer.number %></p>
		<p>	Описание:				<%= customer.description %></p>
 <%= link_to "параметры клиента", customer_path(customer), :class => "btn btn-warning" %>

<hr>
	<% end %>
		
		

	</div	>
<% end %>

app/views/customers/edit.html.erb
<h2>Редактирование данных клиента</h2>
<%= form_for :customer, url: customer_path(customer_url), method: :patch do |f| %>
	<% if @customer.errors.any? %>
		<% @customer.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	<p>
		Имя<br>
		<%= f.text_field(:name, {:class => 'form_control'}) %>
		<% if @customer.errors.any? %>
		<% @customer.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	</p>

	<p>
		Номер телефона<br>
		<%= f.text_field(:number, {:class => 'form_control'}) %>
		<% if @customer.errors.any? %>
		<% @customer.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	</p>

	<p>
		Описание<br>
		<% if @customer.errors.any? %>
		<% @customer.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
		<%= f.text_area(:description, {:class => 'form_control'}) %>
	</p>
	<p> 
		<%= f.submit({:class => 'btn btn-warning'}) %>
	</p>
<% end %>

app/views/customers/index.html.erb
<h2>Cписок клиентов</h2>
<hr>
<% @customer.each do |customer| %>
	<% if customer.blklist == false %>
	<div>
		<h4>Имя:						<%= customer.name %></h4>
		<p> Номер телефона:	<%= customer.number %></p>
		<p>	Описание:				<%= customer.description %></p>
  <%= link_to "параметры клиента", customer_path(customer), :class => "btn btn-warning" %>

<hr>
	<% end %>
		
		

	</div	>
<% end %>

app/views/customers/new.html.erb
<h2>добавление нового клиента</h2>
<%= form_for :customer, url: customers_path do |f| %>
	<% if @customer.errors.any? %>
		<% @customer.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	<p>
		Имя<br>
		<%= f.text_field(:name, {:class => 'form_control'}) %>
		<% if @customer.errors.any? %>
		<% @customer.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	</p>

	<p>
		Номер телефона<br>
		<%= f.text_field(:number, {:class => 'form_control'}) %>
		<% if @customer.errors.any? %>
		<% @customer.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	</p>

	<p>
		Описание<br>
		<% if @customer.errors.any? %>
		<% @customer.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
		<%= f.text_area(:description, {:class => 'form_control'}) %>
	</p>
	<p> 
		<%= f.submit({:class => 'btn btn-warning'}) %>
	</p>
<% end %>

app/views/customers/show.html.erb
<h4>Имя:						<%= @customer.name %></h4>
<p> Номер телефона:	<%= @customer.number %></p>
<p>	Описание:				<%= @customer.description %></p>
<%= link_to 'Редактировать', edit_customer_path(@customer), :class => "btn btn-warning" %>
	<% if @customer.blklist == false %>
<%= link_to "в черный список", :controller => :customers, :action => :toggle_blacklist, customer_id: @customer.id %>
	<%end%>
<% if @customer.blklist == true %>
<%= link_to "из черного списка", :controller => :customers, :action => :toggle_blacklist, customer_id: @customer.id %>
	<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qqq</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

 <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'	  %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
 <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-bold">Наши клиенты</h5>
  <nav class="my-2 my-md-0 mr-md-3">
	<span class="p-2 text-dark" ><%= link_to "Черный список", blacklist_path %></span>
    
	<span class="p-2 text-dark" ><%= link_to "Вернуться к списку", home_path %></span>
  </nav>
  <span class="p-2 text-dark"> <%= link_to "Добавить клиента", new_customer_path %></span>
</div>
<div class="container">
    <%= yield %>
</div>
  </body>
</html>